<?php
defined('MOODLE_INTERNAL') || die;
$functions = array(
   'local_questionbank_view' => array(
     'classname' => 'local_questionbank_external',
     'methodname' => 'questionbankview',
     'classpath'   => 'local/questionbank/classes/external.php',
     'description' => 'List all Questionbank',
     'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
     'ajax' => true,
     'type' => 'read',
    ),
 'local_questionbank_delete' => array(
   'classname' => 'local_questionbank_external',
   'methodname' => 'deletequestionbank',
   'classpath'   => 'local/questionbank/classes/external.php',
   'description' => 'Delete Questionbank',
   'ajax' => true,
   'type' => 'write',
  ),
 'local_questionbank_viewtopics' => array(
   'classname' => 'local_questionbank_external',
   'methodname' => 'viewtopics',
   'classpath'   => 'local/questionbank/classes/external.php',
   'description' => 'View all Topics',
   'ajax' => true,
   'type' => 'read',
  ),
  'local_questionbank_viewcompetencies' => array(
   'classname' => 'local_questionbank_external',
   'methodname' => 'viewcompetencies',
   'classpath'   => 'local/questionbank/classes/external.php',
   'description' => 'View all viewcompetencies',
   'ajax' => true,
   'type' => 'read',
  ),
  'display_competencies' => array(
        'classname' => 'local_questionbank_external',
        'methodname' => 'competenciesinfo',
        'classpath'   => 'local/questionbank/external.php',
        'description' => 'Competencies view',
        'ajax' => true,
        'type' => 'read',
    ), 
 'local_questionbank_unassigntopics' => array(
   'classname' => 'local_questionbank_external',
   'methodname' => 'unassigntopics',
   'classpath'   => 'local/questionbank/classes/external.php',
   'description' => 'View all Experts',
   'ajax' => true,
   'type' => 'read',
  ),
 'local_questionbank_assignexperts' => array(
   'classname' => 'local_questionbank_external',
   'methodname' => 'assignexperts',
   'classpath'   => 'local/questionbank/classes/external.php',
   'description' => 'View all Experts',
   'ajax' => true,
   'type' => 'read',
  ),
 'local_questionbank_viewexperts' => array(
     'classname' => 'local_questionbank_external',
     'methodname' => 'questionbankviewexperts',
     'classpath'   => 'local/questionbank/classes/external.php',
     'description' => 'List all experts',
     'ajax' => true,
     'type' => 'read',
    ),
  'local_questionbank_deletecompetency' => array(
   'classname' => 'local_questionbank_external',
   'methodname' => 'deletecompetency',
   'classpath'   => 'local/questionbank/classes/external.php',
   'description' => 'Delete Questionbank',
   'ajax' => true,
   'type' => 'write',
  ),
   'local_questionbank_deletecourse' => array(
   'classname' => 'local_questionbank_external',
   'methodname' => 'deletecourse',
   'classpath'   => 'local/questionbank/classes/external.php',
   'description' => 'Delete Questionbank',
   'ajax' => true,
   'type' => 'write',
  ),
  'local_questionbank_form_selector'  => array(
  'classname' => 'local_questionbank_external',
  'methodname' => 'form_selector',
  'classpath'   => 'local/questionbank/classes/external.php',
  'description' => 'form_selector',
  'ajax' => true,
  'type' => 'reade',
   ),
  'local_questionbank_topic_selector'  => array(
  'classname' => 'local_questionbank_external',
  'methodname' => 'topic_selector',
  'classpath'   => 'local/questionbank/classes/external.php',
  'description' => 'topic_selector',
  'ajax' => true,
  'type' => 'reade',
   ),
  'local_questionbank_changestatus'  => array(
  'classname' => 'local_questionbank_external',
  'methodname' => 'changequestionstatus',
  'classpath'   => 'local/questionbank/classes/external.php',
  'description' => 'Change Question Status',
  'ajax' => true,
  'type' => 'write',
   ),
  'local_questionbank_assignreviewer'  => array(
  'classname' => 'local_questionbank_external',
  'methodname' => 'assignreviewer',
  'classpath'   => 'local/questionbank/classes/external.php',
  'description' => 'Change Question Status',
  'ajax' => true,
  'type' => 'write',
   ),
  'local_questionbank_displaytopics' => array(
        'classname' => 'local_questionbank_external',
        'methodname' => 'questiontopics',
        'classpath'   => 'local/questionbank/external.php',
        'description' => 'Topics view',
        'ajax' => true,
        'type' => 'read',
    ), 
  'local_questionbank_qbcompetencieslist' => array(
        'classname' => 'local_questionbank_external',
        'methodname' => 'qbcompetencieslist',
        'classpath'   => 'local/questionbank/external.php',
        'description' => 'List of competencies',
        'ajax' => true,
        'type' => 'read',
    ),  
  'local_questionbank_fetch_expertname' => array(
        'classname' => 'local_questionbank_external',
        'methodname' => 'fetch_expertname',
        'classpath'   => 'local/questionbank/external.php',
        'description' => 'List of competencies',
        'ajax' => true,
        'type' => 'read',
    ), 
  'local_bulk_update_question_status' => array(
        'classname' => 'local_questionbank_external',
        'methodname' => 'bulk_update_question_status',
        'classpath'   => 'local/questionbank/external.php',
        'description' => 'Bulk update question status',
        'ajax' => true,
        'type' => 'read',
    ),
  // 'reservequestionsforexpert' => array(
  //           'classname'   => 'local_questionbank_external',
  //           'methodname'  => 'reservequestionsforexpert',
  //           'classpath'   => 'local/questionbank/external.php',
  //           'description' => 'Questions reservation',
  //           'type'        => 'write',
  //           'ajax' => true,
  //   ),

);
