<?php
/**
 * Defines the services of products
 *
 * @package    tool_product
 * @copyright  2022 Naveen kumar <naveen@eabyas.com>
 */
defined('MOODLE_INTERNAL') || die();


$functions = array(
    'tool_product_user_login' => array(
        'classname'     =>  'tool_product_external',
        'methodname'    =>  'user_login',
        'classpath'     =>  'admin/tool/products/classes/external.php',
        'description'   =>  'user login.',
        'type'          =>  'write',
        'capabilities'  =>  'tool/products:view',
        'services'      =>  array(MOODLE_OFFICIAL_MOBILE_SERVICE),
        'ajax'          =>  true,
        'loginrequired' =>  false,
    ),
    'tool_product_view_cart' => array(
        'classname'     =>  'tool_product_external',
        'methodname'    =>  'view_cart',
        'classpath'     =>  'admin/tool/products/classes/external.php',
        'description'   =>  'view cart summary.',
        'type'          =>  'write',
        'capabilities'  =>  'tool/products:checkout',
        'services'      =>  array(MOODLE_OFFICIAL_MOBILE_SERVICE),
        'ajax'          =>  true,
        'loginrequired' =>  false,  
    ),
    'tool_product_checkout_summary' => array(
        'classname'     =>  'tool_product_external',
        'methodname'    =>  'checkout_summary',
        'classpath'     =>  'admin/tool/products/classes/external.php',
        'description'   =>  'view checkout summary.',
        'type'          =>  'write',
        'capabilities'  =>  'tool/products:checkout',
        'services'      =>  array(MOODLE_OFFICIAL_MOBILE_SERVICE),
        'ajax'          =>  true,
        'loginrequired' =>  true,  
    ),
    'tool_product_org_order_payments' => array(
        'classname'     =>  'tool_product_external',
        'methodname'    =>  'org_order_payments',
        'classpath'     =>  'admin/tool/products/classes/external.php',
        'description'   =>  'organization official order payments.',
        'type'          =>  'write',
        'capabilities'  =>  'tool/products:checkout',
        'services'      =>  array(MOODLE_OFFICIAL_MOBILE_SERVICE),
        'ajax'          =>  true,
        'loginrequired' =>  true,  
    ),
    'tool_product_get_post_financialpayments' => array(
      'classname' => 'tool_product_external',
      'methodname' => 'get_post_financialpayments',
      'classpath'   => 'admin/tool/products/classes/external.php',
      'description' => 'get orders financial payments',
      'type' => 'read',
      'services'      =>  array(MOODLE_OFFICIAL_MOBILE_SERVICE),
      'ajax'          =>  true,
      'loginrequired' =>  true,  
    ), 
    'tool_product_get_orders_approval' => array(
      'classname' => 'tool_product_external',
      'methodname' => 'get_orders_approval',
      'classpath'   => 'admin/tool/products/classes/external.php',
      'description' => 'get orders for approvals',
      'type' => 'read',
      'services'      =>  array(MOODLE_OFFICIAL_MOBILE_SERVICE),
      'ajax'          =>  true,
      'loginrequired' =>  true,  
    ), 
    'tool_product_viewpurchases' => array(
      'classname' => 'tool_product_external',
      'methodname' => 'viewpurchases',
      'classpath'   => 'admin/tool/products/classes/external.php',
      'description' => 'View all purchases',
       'services'      =>  array(MOODLE_OFFICIAL_MOBILE_SERVICE),
      'type' => 'write',
      'ajax' => true,
    ),
    'tool_product_validate_couponcode' => array(
        'classname'     =>  'tool_product_external',
        'methodname'    =>  'validate_couponcode',
        'classpath'     =>  'admin/tool/products/classes/external.php',
        'description'   =>  'validate couponcode.',
        'type'          =>  'write',
        'services'      =>  array(MOODLE_OFFICIAL_MOBILE_SERVICE),
        'ajax'          =>  true,
        'loginrequired' =>  false,  
    ),
    'tool_product_telr_begin_trans' => array(
        'classname'     =>  'tool_product_external',
        'methodname'    =>  'telr_begin_trans',
        'classpath'     =>  'admin/tool/products/classes/external.php',
        'description'   =>  'Intiate telr transaction.',
        'services'      =>  array(MOODLE_OFFICIAL_MOBILE_SERVICE),
        'type'          =>  'write',
        'ajax'          =>  true,
    ),
    'tool_product_postpaid_payments' => array(
        'classname'     =>  'tool_product_external',
        'methodname'    =>  'postpaid_payments',
        'classpath'     =>  'admin/tool/products/classes/external.php',
        'description'   =>  'organization official order postpaid payments.',
        'type'          =>  'write',
        'capabilities'  =>  'tool/products:checkout',
        'services'      =>  array(MOODLE_OFFICIAL_MOBILE_SERVICE),
        'ajax'          =>  true,
        'loginrequired' =>  true,  
    ),
    'tool_product_prepaid_payments' => array(
        'classname'     =>  'tool_product_external',
        'methodname'    =>  'prepaid_payments',
        'classpath'     =>  'admin/tool/products/classes/external.php',
        'description'   =>  'organization official order prepaid payments.',
        'type'          =>  'write',
        'capabilities'  =>  'tool/products:checkout',
        'services'      =>  array(MOODLE_OFFICIAL_MOBILE_SERVICE),
        'ajax'          =>  true,
        'loginrequired' =>  true,  
    ),
    'tool_product_get_mypayments' => array(
        'classname'     =>  'tool_product_external',
        'methodname'    =>  'get_mypayments',
        'classpath'     =>  'admin/tool/products/classes/external.php',
        'description'   =>  'get orders payments',
        'type'          =>  'read',
        'services'      =>  array(MOODLE_OFFICIAL_MOBILE_SERVICE),
        'ajax'          =>  true,
        'loginrequired' =>  true,  
    ),

    'tool_product_sendemailtoorgofficial' => array(
        'classname'     =>  'tool_product_external',
        'methodname'    =>  'sendemailtoorgofficial',
        'classpath'     =>  'admin/tool/products/classes/external.php',
        'description'   =>  'get orders payments',
        'type'          =>  'read',
        'ajax'          =>  true,
        'loginrequired' =>  true,  
    ),

    'tool_product_get_mywallet' => array(
        'classname'     =>  'tool_product_external',
        'methodname'    =>  'get_mywallet',
        'classpath'     =>  'admin/tool/products/classes/external.php',
        'description'   =>  'get orders payments',
        'type'          =>  'read',
        'services'      =>  array(MOODLE_OFFICIAL_MOBILE_SERVICE),
        'ajax'          =>  true,
        'loginrequired' =>  true,  
    ),

    'tool_product_get_orgpayments' => array(
        'classname'     =>  'tool_product_external',
        'methodname'    =>  'get_orgpayments',
        'classpath'     =>  'admin/tool/products/classes/external.php',
        'description'   =>  'get orders payments',
        'type'          =>  'read',
        'services'      =>  array(MOODLE_OFFICIAL_MOBILE_SERVICE),
        'ajax'          =>  true,
        'loginrequired' =>  true,  
    ),

    'tool_product_getproductinfo' => array(
        'classname'     =>  'tool_product_external',
        'methodname'    =>  'getproductinfo',
        'classpath'     =>  'admin/tool/products/classes/external.php',
        'description'   =>  'Intiate telr transaction.',
        'services'      =>  array(MOODLE_OFFICIAL_MOBILE_SERVICE),
        'type'          =>  'write',
        'ajax'          =>  true,
    ),

    'tool_product_ordersummary' => array(
        'classname'     =>  'tool_product_external',
        'methodname'    =>  'ordersummary',
        'classpath'     =>  'admin/tool/products/classes/external.php',
        'description'   =>  'Intiate telr transaction.',
        'services'      =>  array(MOODLE_OFFICIAL_MOBILE_SERVICE),
        'type'          =>  'write',
        'ajax'          =>  true,
    ),
    'tool_product_trainee_walletamount' => array(
        'classname'     =>  'tool_product_external',
        'methodname'    =>  'trainee_walletamount',
        'classpath'     =>  'admin/tool/products/classes/external.php',
        'description'   =>  'Trainee Wallet Amount',
        'services'      =>  array(MOODLE_OFFICIAL_MOBILE_SERVICE),
        'type'          =>  'write',
        'ajax'          =>  true,
    ),
    'tool_product_generate_sadadbill' => array(
        'classname'     =>  'tool_product_external',
        'methodname'    =>  'generate_sadadbill',
        'classpath'     =>  'admin/tool/products/classes/external.php',
        'description'   =>  'Generate sadad bill',
        'services'      =>  array(MOODLE_OFFICIAL_MOBILE_SERVICE),
        'type'          =>  'write',
        'ajax'          =>  true,
    ),
    'tool_product_rejectorder' => array(
        'classname'     =>  'tool_product_external',
        'methodname'    =>  'rejectorder',
        'classpath'     =>  'admin/tool/products/classes/external.php',
        'description'   =>  'Admin rejecting orgoff order',
        'services'      =>  array(MOODLE_OFFICIAL_MOBILE_SERVICE),
        'type'          =>  'write',
        'ajax'          =>  true,
    ),
    'tool_product_get_orderinfo' => array(
        'classname'     =>  'tool_product_external',
        'methodname'    =>  'get_orderinfo',
        'classpath'     =>  'admin/tool/products/classes/external.php',
        'description'   =>  'Admin approving orgoff order',
        'services'      =>  array(MOODLE_OFFICIAL_MOBILE_SERVICE),
        'type'          =>  'write',
        'ajax'          =>  true,
    ),
);
