<?php
defined('MOODLE_INTERNAL') || die();
function xmldb_local_exams_install(){
	global $CFG, $USER, $DB, $OUTPUT;
	$dbman = $DB->get_manager(); // loads ddl manager and xmldb classes
 	$time = time();  
    $category = array('name' => 'Exam', 'idnumber' => 'exams', 'description' => 'This category is related to  Exams','parent' => '0', 'visible' => 1, 'depth' => 1, 'timemodified' => $time);
    $category = core_course_category::create($category);

    if (!defined('BEHAT_SITE_RUNNING') && !(defined('PHPUNIT_TEST') && PHPUNIT_TEST)) {
        \tool_certificate\certificate::create_exam_template();
    }
    $table = new xmldb_table('refund_settings');
    if($dbman->table_exists($table)){
        $time = time();
        $record = new stdClass();
        $record->type = 'cancel';
        $record->entitytype = 'exam';
        $record->dayfrom = 0;
        $record->dayto = 6;
        $record->dedtype = 0;
        $record->dedpercentage = 100;
        $record->dedamount = null;
        $record->timecreated = $time;
        $record->usercreated = 2;
        $record->userid = 2;
        $record->timemodified = 0;
        $record->usermodified = 0;
        $DB->insert_record('refund_settings',$record);
        $time = time();
        $record->type = 'cancel';
        $record->entitytype = 'exam';
        $record->dayfrom = 7;
        $record->dayto = 14;
        $record->dedtype = 0;
        $record->dedpercentage = 50;
        $record->dedamount = null;
        $record->timecreated = $time;
        $record->usercreated = 2;
        $record->userid = 2;
        $record->timemodified = 0;
        $record->usermodified = 0;
        $DB->insert_record('refund_settings',$record);
        $time = time();
        $record->type = 'cancel';
        $record->entitytype = 'exam';        
        $record->dayfrom = 15;
        $record->dayto = 30;
        $record->dedtype = 0;
        $record->dedpercentage = 25;
        $record->dedamount = null;
        $record->timecreated = $time;
        $record->usercreated = 2;
        $record->userid = 2;
        $record->timemodified = 0;
        $record->usermodified = 0;
        $DB->insert_record('refund_settings',$record);
        $time = time();
        $record->type = 'cancel';
        $record->entitytype = 'exam';        
        $record->dayfrom = 31;
        $record->dayto = 334;
        $record->dedtype = 0;
        $record->dedpercentage = 0;
        $record->dedamount = null;
        $record->timecreated = $time;
        $record->usercreated = 2;
        $record->userid = 2;
        $record->timemodified = 0;
        $record->usermodified = 0;
        $DB->insert_record('refund_settings',$record);

        $time = time();
        $record = new stdClass();
        $record->type = 'reschedule';
        $record->entitytype = 'exam';
        $record->dayfrom = 8;
        $record->dayto = 358;
        $record->dedtype = 1;
        $record->dedpercentage = null;
        $record->dedamount = 100;
        $record->timecreated = $time;
        $record->usercreated = 2;
        $record->userid = 2;
        $record->timemodified = 0;
        $record->usermodified = 0;
        $DB->insert_record('refund_settings',$record);
        $time = time();
        $record->type = 'reschedule';
        $record->entitytype = 'exam';        
        $record->dayfrom = 3;
        $record->dayto = 7;
        $record->dedtype = 0;
        $record->dedpercentage = 50;
        $record->dedamount = NULL;
        $record->timecreated = $time;
        $record->usercreated = 2;
        $record->userid = 2;
        $record->timemodified = 0;
        $record->usermodified = 0;        
        $DB->insert_record('refund_settings',$record);
        //  Rescheduling policies for CISI (for First Attempt)
        $time = time();
        $record->type = 'reschedule';
        $record->entitytype = 'exam';
        $record->ownedbycisi = 1;
        $record->moreattempts = 0;
        $record->dayfrom = 15;
        $record->dayto = 350;
        $record->dedtype = 1;
        $record->dedpercentage = NULL;
        $record->dedamount = 0;
        $record->timecreated = $time;
        $record->usercreated = 2;
        $record->userid = 2;
        $record->timemodified = 0;
        $record->usermodified = 0;        
        $DB->insert_record('refund_settings',$record);

        $time = time();
        $record->type = 'reschedule';
        $record->entitytype = 'exam';
        $record->ownedbycisi = 1;
        $record->moreattempts = 0;
        $record->dayfrom = 2;
        $record->dayto = 14;
        $record->dedtype = 1;
        $record->dedpercentage = NULL;
        $record->dedamount = 100;
        $record->timecreated = $time;
        $record->usercreated = 2;
        $record->userid = 2;
        $record->timemodified = 0;
        $record->usermodified = 0;        
        $DB->insert_record('refund_settings',$record);
        //  Rescheduling policies for CISI (for More than First Attempt)
        $time = time();
        $record->type = 'reschedule';
        $record->entitytype = 'exam';
        $record->ownedbycisi = 1;
        $record->moreattempts = 1;
        $record->dayfrom = 3;
        $record->dayto = 362;
        $record->dedtype = 0;
        $record->dedpercentage = 100;
        $record->dedamount = NULL;
        $record->timecreated = $time;
        $record->usercreated = 2;
        $record->userid = 2;
        $record->timemodified = 0;
        $record->usermodified = 0;        
        $DB->insert_record('refund_settings',$record);
        // Exam Replacement policies for FA
        $time = time();
        $record = new stdClass();
        $record->type = 'replace';
        $record->entitytype = 'exam';
        $record->dayfrom = 0;
        $record->dayto = 2;
        $record->dedtype = 1;
        $record->dedpercentage = null;
        $record->dedamount = 100;
        $record->timecreated = $time;
        $record->usercreated = 2;
        $record->userid = 2;
        $record->timemodified = 0;
        $record->usermodified = 0;
        $DB->insert_record('refund_settings',$record);           
    }
}
