<?php
defined('MOODLE_INTERNAL') || die;
$functions = array(
    'local_deletehall' => array(
            'classname'   => 'local_hall_external',
            'methodname'  => 'delete_hall',
            'classpath'   => 'local/hall/classes/external.php',
            'description' => 'delete data',
            'type'        => 'write',
            'ajax' => true,
    ),
    'local_halls_view' => array(
        'classname' => 'local_hall_external',
        'methodname' => 'halls_view',
        'classpath' => 'local/hall/classes/external.php',
        'description' => 'List all courses in card view',
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
        'ajax' => true,
        'type' => 'read',
    ),
    'local_hall_info' => array(
            'classname'   => 'local_hall_external',
            'methodname'  => 'hall_info',
            'classpath'   => 'local/hall/classes/external.php',
            'description' => 'organization details',
            'type'        => 'write',
            'ajax' => true,
    ),
    'local_reservation_view' => array(
            'classname'   => 'local_hall_external',
            'methodname'  => 'reservation_info',
            'classpath'   => 'local/hall/classes/external.php',
            'description' => 'reservation details',
            'type'        => 'write',
            'ajax' => true,
    ),
    'local_hall_reservation' => array(
            'classname'   => 'local_hall_external',
            'methodname'  => 'hall_reservation',
            'classpath'   => 'local/hall/classes/external.php',
            'description' => 'hall reservation',
            'type'        => 'write',
            'ajax' => true,
    ),
    'local_hall_data' => array(
            'classname'   => 'local_hall_external',
            'methodname'  => 'hall_data',
            'classpath'   => 'local/hall/classes/external.php',
            'description' => 'hall reservation',
            'type'        => 'write',
            'ajax' => true,
    ),
    'hall_slotbooking' => array(
            'classname'   => 'local_hall_external',
            'methodname'  => 'hall_slotbooking',
            'classpath'   => 'local/hall/classes/external.php',
            'description' => 'hall reservation',
            'type'        => 'write',
            'ajax' => true,
    ),
    'local_schedule_view' => array(
            'classname'   => 'local_hall_external',
            'methodname'  => 'schedule_view',
            'classpath'   => 'local/hall/classes/external.php',
            'description' => 'hall reservation',
            'type'        => 'write',
            'ajax' => true,
    ),
    'local_hallreservation_view' => array(
            'classname'   => 'local_hall_external',
            'methodname'  => 'hallreservation_view',
            'classpath'   => 'local/hall/classes/external.php',
            'description' => 'hall reservation',
            'type'        => 'write',
            'ajax' => true,
    ),
    'local_hallinfo_view' => array(
            'classname'   => 'local_hall_external',
            'methodname'  => 'hallinfo_view',
            'classpath'   => 'local/hall/classes/external.php',
            'description' => 'hall reservation',
            'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),            
            'type'        => 'write',
            'ajax' => true,
    ),
    'local_scheduledhalls'  => array(
            'classname'   => 'local_hall_external',
            'methodname'  => 'currenthalls',
            'classpath'   => 'local/hall/classes/external.php',
            'description' => 'hall reservation',
            'loginrequired' => false,
            'type'        => 'write',
            'ajax' => true,
    ), 

    //Vinod- Hall fake block for communication officer - Starts//   
    'local_hall_manage_halls_block' => array(
        'classname'   => 'local_hall_external',
        'methodname'  => 'hallsblock',
        'classpath'   => 'local/hall/classes/external.php',
        'description' => 'List of halls fake block',
        'type'        => 'write',
        'ajax' => true,
    ),
    'local_entity_search' => array(
        'classname' => 'local_hall_external',
        'methodname' => 'entities_search',
        'classpath' => 'local/hall/classes/external.php',
        'description' => 'List all courses in card view',
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
        'ajax' => true,
        'type' => 'read',
    ), 

    'local_halls_schedulehallsview' => array(
        'classname' => 'local_hall_external',
        'methodname' => 'schedulehall_view',
        'classpath' => 'local/hall/classes/external.php',
        'description' => 'List of schedule hall',
        'ajax' => true,
        'type' => 'read',
    ),    
    'local_deleteschedulehall' => array(
            'classname'   => 'local_hall_external',
            'methodname'  => 'deleteschedulehall',
            'classpath'   => 'local/hall/classes/external.php',
            'description' => 'delete data',
            'type'        => 'write',
            'ajax' => true,
    ),
);
